### ISSUE TITLE
Error Register Response

### ISSUE THREAD

**Issue by tadeegan** [square/SquareRegisterSDK-iOS#6]
Error Domain=SCCAPIErrorDomain Code=17 "(null)" UserInfo={error_code=client_not_authorized_for_user}

I am getting this error.  I think it is because I need to have the client approve my application with OAuth.  Why isn't this documented here?  Why is there nothing in the sample app?

**Comment by theinventor** [comment]
+1

**Comment by StephenBarlow** [comment]
Thanks for pointing out this omission in the documentation. You are correct that this error is occurring because the merchant has not yet authorized your application to act on their behalf. Please see [this section of the documentation](https://docs.connect.squareup.com/articles/register-api-ios/#authorizingregisterapplication) for more information.
